### ISSUE TITLE
AssertionError: Oases failed at k = 25

### ISSUE THREAD

**Issue by Peajee** [dzerbino/oases#10]
I have a Problem with Oases and could not find anything helpful anywhere else. That is why I am reporting my problem here. Please forgive me, if this is the wrong place to ask or I have simply overlooked something very simple.

**When running the following command:**
python /home/user/oases/scripts/oases_pipeline.py -m 25 -M 35 -s 4 -o oases -d ' -shortPaired -separate -fastq /work/user/All_Samples/12m/data_1.fq /work/user/All_Samples/12m/data_2.fq' -p '-min_trans_lgth 300'

**I get this error:**

Traceback (most recent call last):
  File "/home/user/oases/scripts/oases_pipeline.py", line 130, in <module>
    main()
  File "/home/user/oases/scripts/oases_pipeline.py", line 124, in main
    singleKAssemblies(options)
  File "/home/user/oases/scripts/oases_pipeline.py", line 55, in singleKAsse$
    assert p.returncode == 0, "Oases failed at k = %i\n%s" % (k, output[0])
AssertionError: Oases failed at k = 25

I can not make heads or tails of it. What is the Problem here?

**Comment by dzerbino** [comment]
Could you please print out the entire stderr output?

Thank you,

Daniel

**Comment by Peajee** [comment]
Hi Daniel.
Thanks for your reply.

I'm running Oases on a SLURM Grid (because our local computers are not powerful enough) and according to the SLURM-Stderr-Outputfile, the above mentioned error is the only Stderr output apart from:
module: loaded site/slurm
module: loaded site/tmpdir
module: loaded env/system-gcc

So the entire Stderr Output reads:

module: loaded site/slurm
module: loaded site/tmpdir
module: loaded env/system-gcc
Traceback (most recent call last):
  File "/home/user/oases/scripts/oases_pipeline.py", line 130, in <module>
    main()
  File "/home/user/oases/scripts/oases_pipeline.py", line 124, in main
    singleKAssemblies(options)
  File "/home/user/oases/scripts/oases_pipeline.py", line 55, in singleKAsse$
    assert p.returncode == 0, "Oases failed at k = %i\n%s" % (k, output[0])
AssertionError: Oases failed at k = 25

The "Log" file in the "oases_25" Output Directory reads:

Thu Jun 23 10:45:23 2016
 velveth oases 25,39,4 -shortPaired -separate -fastq /work/user/All_Samples/12m/data_1.fq /work/user/All_Samples/12m/data_2.fq
Version 1.2.10
Copyright 2007, 2008 Daniel Zerbino (zerbino@ebi.ac.uk)
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Compilation settings:
CATEGORIES = 15
MAXKMERLENGTH = 150
OPENMP
LONGSEQUENCES
BIGASSEMBLY

Thu Jun 23 10:57:05 2016
 velvetg oases_25 -read_trkg yes
Version 1.2.10
Copyright 2007, 2008 Daniel Zerbino (zerbino@ebi.ac.uk)
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Compilation settings:
CATEGORIES = 15
MAXKMERLENGTH = 150
OPENMP
LONGSEQUENCES
BIGASSEMBLY

Final graph has 6973970 nodes and n50 of 128, max 2306, total 209646759, using 6701048/12473522 reads
Thu Jun 23 12:12:53 2016
 oases oases_25 -min_trans_lgth 300
Version 1.2.10
Copyright 2007, 2008 Daniel Zerbino (zerbino@ebi.ac.uk)
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Compilation settings:
CATEGORIES = 80
MAXKMERLENGTH = 70
OPENMP
LONGSEQUENCES
BIGASSEMBLY

I thought it was weird, that there are two different settings for Categories and MaxKmerlength. I was equally surprised by the Logfile naming 25 to 39 as the intervall for the assemblies (although 35 was provided by me in the command) and the creation of folders oases_25-oases_37. 

Is this due to something I am doing wrong?

**Comment by dzerbino** [comment]
Indeed, could you please recompile Oases to have the same parameters as Velvet? This discrepancy would cause a fair number of bugs.

**Comment by Peajee** [comment]
I am feeling quite awkward and I am very sorry to have bothered you with this!
The Problem seems to have indeed been the incorrect compilation of Velvet/Oases.

But thank you very much for taking your time and helping me with this!

After compiling both Oases and Velvet I ran a Test-Assembly with a small dataset (12 million reads), which finished without a hitch. But when running the full Assembly (with 300 million reads) I got another Error after nearly three days of runtime (see files attached). I am assuming, this is simply due to memory limitations (as stated in the first line of output)?
[slurm-36256.txt](https://github.com/dzerbino/oases/files/334994/slurm-36256.txt)
[Log.txt](https://github.com/dzerbino/oases/files/334995/Log.txt)

**Comment by dzerbino** [comment]
No problem. 

Yes, this is a memory allocation problem. Velvet has its own memory allocation, which allocates memory by block (in this case 49127940 B). This memory allocation happens as it is required, so memory consumption is not constant.

**Comment by Peajee** [comment]
Thank you very much!
