### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by winni2k** [dzerbino/oases#14]
Can I get a bit of clarification on this part of the [coverage cutoff section](https://github.com/dzerbino/oases#coverage-cutoff) of the documentation?

> Instead, the coverage cutoff is set to remove all the contigs whose coverage is so low that de novo assembly would be impossible anyways (by default it is set at 3x).

1. Is the coverage cutoff applied to the average of the k-mer coverage of each contig?
2. Are the contigs that the coverage cutoff is applied to also unitigs?
3. Does "3x" refer to an average contig coverage below 3?

**Comment by dzerbino** [comment]
Yes to all 3. 

HTH,

@dzerbino

**Comment by winni2k** [comment]
Excellent, thanks!
