### ISSUE TITLE
Behavior of oases with duplicate removal

### ISSUE THREAD

**Issue by winni2k** [dzerbino/oases#15]
Is my understanding correct that the original oases paper does not look at duplicate read removal (before trimming)?
Has anyone else evaluated the effect of duplicate read removal on oases?
I would expect the hard threshold of 3 on mean unitig coverage might have to be re-evaluated?

**Comment by dzerbino** [comment]
Hello @winni2k,

No, we did not look into duplicate read removal, but you should contact Marcel Schulz, who has looked far more into pre-processing before running Oases.

The threshold of 3 was indeed quite arbitrary, but proved very useful to remove the more egregiously low confidence assemblies. 

Regards,

Daniel

**Comment by winni2k** [comment]
Cheers.
