### ISSUE TITLE
Loss of strand-specificity

### ISSUE THREAD

**Issue by jrodnz** [dzerbino/oases#17]
I have been trying to de novo assemble some strand-specific 100 bp PE mRNA-seq data using the overassembly+evigene approach. However, even though I run oases with the strand_specific option, some of the outputted transcripts appear to have the wrong strand orientation. Could you please look through my methodology and let me know if I am doing something wrong? Thanks for your time!

---

Data: Hexaploid blueberry
De novo assemblers compared: 
* Trinity (2.6.5)
* SOAPdenovoTrans (1.03)
* Oases (0.2.09, with Velvet 1.2.10)

Comparison method: Map to related diploid blueberry genome with GMAP (2018-05-11) and compare with hexaploid RNA-seq reads mapped to the genome with STAR (2.5.3a)

~~~
# Command
INPUT=05.Trinity/Flesh_trinity/insilico_read_normalization
python oases_pipeline.py \
    -m 23 -M 23 -o Flesh-pipeline23 \
    -d ' -fastq -separate -strand_specific -shortPaired $INPUT/left.norm.fq $INPUT/right.norm.fq ' \
    -p ' -ins_length 150 -ins_length_sd 90 
~~~

Example of assembled transcripts with incorrect strand-orientation:
![scaffold1_127500-142000_denovoasmblrscomp](https://user-images.githubusercontent.com/36523665/40759612-5c98e964-6482-11e8-934f-eafe3b15ae56.png)
Orange blocks indicate ORFs, red blocks indicate transcripts (exon information excluded for clarity). Reads shown are from one of three libraries used as input. Trinity assembly = Flesh_trinity; SOAP assembly = 20180524...; Oases assembly = Flesh_oasespip... Trinity did the best job of assembling transcripts with the right strand-specificity, followed by SOAP (which seems not to take strand-specificity into account when assembling).

**Comment by dzerbino** [comment]
Hello @jrodnz,

Apologies for the slow response. As far as I can tell, you are doing things right, I'm not clear why the transcripts flipped orientation. Naive question: on what strands are the reads in this protocol, forward or reverse?

Cheers,

Daniel

**Comment by jrodnz** [comment]
Hi Daniel,

Thanks for the response! I should have commented earlier, but I ended up figuring out the (at least) two things I was doing wrong: 
1. I was not running gmap with -z sense_force or -z antisense_force, so it was automatically flipping some but not all transcripts based on splice junction orientation (eg. monoexonic transcripts, assembly/genome errors were left as is). There may also be bugs in my gmap installation, as -z antisense_force for some transcripts produced the same strand orientation as -z sense_force!
2. I didn't realize that, since library prep strand orientation isn't specified for Oases, output orientation is based on the R1 read rather than R2 (our library prep used the Lexogen Sense mRNA kit which, like the widely used dUTP protocol, results in antisense R1 and sense R2 reads). On the other hand, orientation of my Trinity output matched the original mRNA, which is probably why gmap had less problems with it.

Both assembly and mapping may also have been complicated by the polyploid nature of the sample, leading to further differences between Oases and Trinity output. Trinity may be slightly better at distinguishing transcripts of highly homologous sequences, but Oases catches some things that Trinity misses, and the speed and kmer flexibility are great.

In the end, Oases does do a good job of retaining strand-specifity! So, thanks for a great tool that complements other efforts in the field :)

Cheers,
Jessica
