### ISSUE TITLE
Definition of -ins_length2 option

### ISSUE THREAD

**Issue by winni2k** [dzerbino/oases#19]
I am confused about what value to use for the `-ins_length2` option of `oases`. Does `-ins_length2` refer to the "insert" length or "inner mate" length as defined [here](http://thegenomefactory.blogspot.com/2013/08/paired-end-read-confusion-library.html)?

**Comment by dzerbino** [comment]
This is inherited from [Velvet's options ](https://github.com/dzerbino/velvet/wiki/Manual) and corresponds to a second library of paired end reads, declared under -shortPaired2.
