### ISSUE TITLE
Bug in AMOS output

### ISSUE THREAD

**Issue by dzerbino** [dzerbino/oases#2]
See mail by Quentin Kaas

**Comment by tseemann** [comment]
@dzerbino Can you paste the content of the email here?

**Comment by dzerbino** [comment]
Quentin wrote:

I tried the forked version but I have the regret to say there are still some problems. In the new version the offsets of all the contigs are all set to 0 and not to their position on the contig... (the "off" element in the TLE definitions in the SCF definitions)
Example:
{SCF
eid:12-0
{TLE
off:0
clr:0,451
src:19
}
{TLE
off:0
clr:0,571
src:20
}
}
