### ISSUE TITLE
Velveth: does not seem to be in fastA format

### ISSUE THREAD

**Issue by shankar2318** [dzerbino/oases#22]
I am trying to use the oases_pipeline.py for a denovo assembly. However, I am getting an error that says the file is not in fastA format. I am not sure about this since I used the same files in other programs for denovo assemblies (RNAbloom, Trinity, Transabyss). I was hoping to know if you could help me resolve this issue. 

Error:
`
velveth: /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024736_1q.fastq does not seem to be in FastA format
Traceback (most recent call last):
  File "/home/shankar2318/software/oases/scripts/oases_pipeline.py", line 130, in <module>
    main()
  File "/home/shankar2318/software/oases/scripts/oases_pipeline.py", line 124, in main
    singleKAssemblies(options)
  File "/home/shankar2318/software/oases/scripts/oases_pipeline.py", line 48, in singleKAssemblies
    assert p.returncode == 0, output[0] + "Hash failed\n"
AssertionError: Hash failed
`

Script:
`#$ -S /bin/bash
#$ -cwd
/home/shankar2318/software/oases/scripts/oases_pipeline.py -m 15 -M 151 -o /home/shankar2318/oases_ncbi -d '-shortPaired /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024736_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024736_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024737_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024737_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024738_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/DRR024738_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813560_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813560_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813561_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813561_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813562_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813562_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813563_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813563_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813564_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813564_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813565_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813565_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813566_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813566_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813567_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813567_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813568_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813568_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813569_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813569_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813570_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813570_2q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813571_1q.fastq /home/shankar2318/sra_dj_trans/ncbi_fasta/trimmed/SRR5813571_2q.fastq'
`

**Comment by dzerbino** [comment]
Dear @shankar2318 ,

The filename `DRR024736_1q.fastq` suggests that is in FastQ format, which is [different from FastA](https://bioinformatics.stackexchange.com/questions/14/what-is-the-difference-between-fasta-fastq-and-sam-file-formats). [Transforming FastQ into FastA](https://bioinformaticsworkbook.org/dataWrangling/fastaq-manipulations/converting-fastq-format-to-fasta.html#gsc.tab=0) is pretty simple with a bit of scripting (ideally using biopython or similar libraries, but you can also "roll your own" with regular expressions). 

Best regards,

Daniel
