### ISSUE TITLE
Slow merge

### ISSUE THREAD

**Issue by dzerbino** [dzerbino/oases#3]
See mail by Dan McMillan

**Comment by tseemann** [comment]
@dzerbino Can you paste the content of the email here?

**Comment by dzerbino** [comment]
Dan MacMillan wrote:

Hi, I had one more inquiry. I was running the oases merge stage on kmers 53-95 in steps of two, I found that it had not yet completed over a period of two weeks. The two fastq files are human, paired end, strand specific, and about 20G each. This type of runtime doesn't seem normal, is there a parameter I can enable to speed up the process? Will setting the cov_cutoff higher help?

(On version 0.2.08)

**Comment by SophieS9** [comment]
Can I check whether this issue has been looked at? I'm also finding that oases merge is taking over two weeks to complete when merging three kmers (25,55,85) on assemblies from the Cat Flea (paired end MiSeq data, with reads that overlap merged and duplicates removed). The initial assemblies for each kmer ran very quickly. I've set cov_cutoff to 10 to try and help speed it up but not sure if it's making much difference.
