### ISSUE TITLE
oases_pipeline.py: incorrect range in singleKAssemblies

### ISSUE THREAD

**Issue by sammyjava** [dzerbino/oases#5]
I got the following error running oases_pipeline.py:
```
$ oases_pipeline.py -m 17 -M 32 -o oases -d ' -shortPaired -separate -fastq.gz test_1.fq.gz test_2.fq.gz ' -p ' -ins_length 480 '
velvetg: Could not write to oases_33/Log: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/oases_pipeline.py", line 121, in <module>
    main()
  File "/usr/local/bin/oases_pipeline.py", line 115, in main
    singleKAssemblies(options)
  File "/usr/local/bin/oases_pipeline.py", line 43, in singleKAssemblies
    assert p.returncode == 0, "Velvetg failed at k = %i\n%s" % (k, output[0])
AssertionError: Velvetg failed at k = 33
```
Looks like the culprit is the ```+options.kstep``` in singleKAssemblies, which sends velvetg to one higher k value than allowed. I changed the range to:
```
for k in range(options.kmin, options.kmax, options.kstep):
```
at line 40 and that fixed it. oases_17 through oases_31 all contain transcripts.fa.

**Comment by sammyjava** [comment]
Oh, ```+options.kstep``` is in two more places, which I also had to fix to get the rest of the script to work, lines 37 and 49. Since the policy is to enter an open-ended range for k, I don't see why ```kmax+options.kstep``` was there. But these three edits resulted in the script running without error and generating the merged assembly. (Great tool! Seems like a lot of folks use it, too.)

**Comment by tseemann** [comment]
I think the problem is that you are choosing M (--kmax) to be an even number. Only odd numbers are valid k-mers in Velvet/Oases. I have added parameter checks to the script now.
