### ISSUE TITLE
Add velvet repository as a sub-module

### ISSUE THREAD

**Issue by tseemann** [dzerbino/oases#6]
Marcel & Daniel

I am trying to package Oases for the Brew system. 

However, the requirement to separately link into the Velvet src dir is problematic. Could you please add the Velvet git repository as a sub-module of the Oases one, so a "git clone --recursive" will compile it out of the box?

Torsten

**Comment by tseemann** [comment]
I've actually now forked it and done this, and started cleaning up the Makefile:
https://github.com/tseemann/oases

Maybe you can add me as a user 'tseemann' to this project and I will make a proper release?

**Comment by dzerbino** [comment]
Thanks a lot!

I just added you.

Daniel
